window.__EXAM_BUILDER_EXAMPLE_CONFIG__ = {
  SUPABASE_URL: 'https://tzpnqvuyksxrrbrxlcxe.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cG5xdnV5a3N4cnJicnhsY3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNjA5MjEsImV4cCI6MjA3NjgzNjkyMX0.UUrd8OSlaBPuNDcRSJIvYS4jzEKvLv95wqPVL7aOg5g',
};